linters-settings:
  misspell:
    locale: US
  lll:
    line-length: 120

linters:
  enable:
    - megacheck
    - golint
    - govet
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
    - stylecheck
    - gochecknoinits
    - scopelint
    - gocritic
    - nakedret
    - gosimple
    - prealloc
  fast: false
  disable-all: true

  service:
    golangci-lint-version: 1.23.x
